## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 

If students address the detailed feedback in a future checkpoint they will earn these points back


|                  | Unsatisfactory                                                                                                                                                                                                    | Developing                                                                                                                                                                                              | Proficient                                     | Excellent                                                                                                                              |
|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| Data relevance   | Did not have data relevant to their question. Or the datasets don't work together because there is no way to line them up against each other. If there are multiple datasets, most of them have this trouble | Data was only tangentially relevant to the question or a bad proxy for the question. If there are multiple datasets, some of them may be irrelevant or can't be easily combined.                       | All data sources are relevant to the question. | Multiple data sources for each aspect of the project. It's clear how the data supports the needs of the project.                         |
| Data description | Dataset or its cleaning procedures are not described. If there are multiple datasets, most have this trouble                                                                                              | Data was not fully described. If there are multiple datasets, some of them are not fully described                                                                                                      | Data was fully described                       | The details of the data descriptions and perhaps some very basic EDA also make it clear how the data supports the needs of the project. |
| Data wrangling   | Did not obtain data. They did not clean/tidy the data they obtained.  If there are multiple datasets, most have this trouble                                                                                 | Data was partially cleaned or tidied. Perhaps you struggled to verify that the data was clean because they did not present it well. If there are multiple datasets, some have this trouble | The data is cleaned and tidied.                | The data is spotless and they used tools to visualize the data cleanliness and you were convinced at first glance                      |

# COGS 108 - Data Checkpoint

## Authors

- Ynna Cate: Conceptualization, Analysis, Data curation, Writing - original draft
- Nicole Go: Software, Data curation, Data curation, Writing - original draft
- Jeric Olan: Background research, Data curation, Writing - original draft
- Abby Rapada: Visualization, Project administration, Data curation, Writing - review & editing
- Xinrui Lyu:

## Research Question

Is there a relationship between street/pothole repair requests and  city property costs in San Diego between the years of 2017 and 2022? Using the relationship seen in those 6 years, are we able to predict the frequency of pothole repair requests by observing the cost of city property and traffic volumes in San Diego?

## Background and Prior Work

The prevalence of potholes in San Diego is a topic of frustration for many, if not most San Diegan drivers. Within the 2,800 miles of streets and roads in San Diego, there are over 40,000 potholes that are repaired every year. <a name="cite_ref-1"></a>[<sup>1</sup>](#cite_note-1). In San Diego, potholes most commonly arise when water seeps under pavement and weakens the integrity of the road. With the constant passage of traffic, the vibrations of vehicles driving over these weakened spots eventually break the pavement resulting in a new pothole. <a name="cite_ref-2"></a>[<sup>2</sup>](#cite_note-2). Thus, in order to reasonably predict the occurrence of potholes and the repair requests they garner, an understanding of the relationship between request frequency, weather patterns, and traffic volume must be considered. In addition, the resolution time of repair tickets may be predicted by patterns of economic growth of certain cities as well as prolonged wet periods in San Diego.




Most of the previous work related to potholes relate to the detection of potholes and not the prediction of onset/complaint. Importantly, many of the works agree that weather and traffic patterns contribute to the risk of pothole creation. One such paper focuses its research on using machine learning and in-vehicle cameras to capture 2D images of potholes and their respective size <a name="cite_ref-3"></a>[<sup>3</sup>](#cite_note-3). Related to potholes, machine learning may also be used to predict Concrete Pavement Condition Index (CPCI). A study based in South Korea seeks for more effective road management by developing a way to accurately predict the rate of degradation of concrete pavement <a name="cite_ref-4"></a>[<sup>4</sup>](#cite_note-4). Perhaps the most similar study based its work in pothole prediction based on pavement condition indicators. This article found that the formation of potholes are mostly unpredictable and due to a multitude of conditions and dominant defects such as surface cracking and the condition of the surrounding pavement <a name="cite_ref-5"></a>[<sup>5</sup>](#cite_note-5).




Though these previous studies overall differ from our focus, they are nevertheless critical to our understanding of the risks of potholes as well as the importance of predictive action. They also offer more solution based literature that may only improve with the continuing development of machine learning. These works also highlight the intricacies of predicting infrastructure conditions. Thus, we acknowledge that our study is bound to many limitations and confounding factors as well as having an insufficient scale to consider many of the possible contributing factors to our question. For instance, given our present data, our focus is on pothole repair requests and not objective pothole frequency. Using repair requests as a proxy for pothole frequency has limitations in that it is not telling of pothole onset. Repeating requests may also be present. If provided a longer time-frame and sufficient resources, our current project may aim to consider more contributors to pothole formation as well as repair promptness.




1. <a name="cite_note-1"></a> [^](#cite_ref-1) Street resurfacing and Pothole Repair. Street Resurfacing and Pothole Repair | City of San Diego Official Website. https://www.sandiego.gov/street-div/services/street-resurfacing-pothole-repair
2. <a name="cite_note-2"></a> [^](#cite_ref-2) Road maintenance. County of San Diego. https://www.sandiegocounty.gov/content/sdc/dpw/roads/surface.html
3. <a name="cite_note-3"></a> [^](#cite_ref-3) Ruseruka, C., Mwakalonge, J., Comert, G., Siuhi, S., NGENI, F., & Anderson, Q. (2023). Augmenting Roadway Safety with Machine Learning and Deep Learning: Pothole Detection and Dimension Estimation Using in-Vehicle Technologies. https://doi.org/10.2139/ssrn.4655731
4. <a name="cite_note-4"></a> [^](#cite_ref-4) Lee, J.-H., Jung, D.-H., Lee, M.-S., & Jeon, S.-I. (2022, August 31). A feasibility study for the prediction of Concrete Pavement Condition index (CPCI) based on machine learning. MDPI. https://www.mdpi.com/2076-3417/12/17/8731
5. <a name="cite_note-5"></a> [^](#cite_ref-5) Pothole prediction based on machine learning and pavement 1. https://publications.aston.ac.uk/id/eprint/47761/1/Pothole_prediction_based_on_machine_learning_and_pavement_condition_indicators_AAM.pdf

## Hypothesis

We predict a strong correlation between the number of potholes repair requests and traffic volume and city property costs in San Diego County. Property costs metrics include start dates, the cost of the lease, location, and type of lease (e.g. house rental, permit, agreement, etc.) Specifically, we predict that higher traffic volumes and higher property cost correlate with a greater frequency of pothole requests.

## Data

### Data overview

- Dataset #1
  - Dataset Name: 
    - Traffic Volumes
  - Link to the dataset: 
    - https://data.sandiego.gov/datasets/traffic-volumes/
  - Number of observations:
    - 13690
  - Number of variables: 
    - 10
  - Variables most relevant to this project:
    - street_name: The street vehicles were counted on
    - limits: Cross streets vehicles were counted between
    - total_count: Total count of vehicles traveling in all directions (north, south, east, west) in 24 hrs
    - count_date: The date vehicles were counted
  - Shortcomings this dataset has with respect to the project:
    - This dataset's dates range from January 05, 2005 to Novemeber 22, 2022. This may limit the recency of the date we can look at for our predictions and not reflect patterns that may have emerged between then and the present. 

- Dataset #2
  - Dataset Name:
    - Prices
  - Link to the dataset:
    - https://seshat.datasd.org/city_owned_properties_leases/city_property_leases_datasd.csv
  - Number of observations:
    - 814
  - Number of variables:
    - 14
  - Variables most relevant to this project:
    - address_zip: Zip code of the lease
    - cost_line_amt_USD: Amount of lease payments
    - effective_date: date of lease effective
    - sched_termination_date: scheduled date for the lease to be terminated
  - Shortcomings this dataset has with respect to the project:
    - This dataset doesn't encapsulate all of the properties within San Diego County.
    - This dataset will be combined with traffic to optimize the chances of a pothole request being put in. 

- Dataset #3
  - Dataset Name:
    - Pothole Requests
  - Link to the dataset:
    - https://data.sandiego.gov/datasets/gid-pothole/
  - Number of observations:
    - 13690
  - Number of variables:
    - 10
  - Variables most relevant to this project:
    - street_name: The street vehicles were counted on
    - limits: Cross streets vehicles were counted between
    - total_count: Total count of vehicles traveling in all directions (north, south, east, west) in 24 hrs
    - count_date: The date vehicles were counted
  - Shortcomings this dataset has with respect to the project:
    - This dataset's dates range from January 09, 2017 to May 12, 2026. January 09, 2017 serves as the minimum date we may use between all of our data sets. We may lose potential patterns that may have emerged before 2017.

Each dataset deserves either a set of bullet points as above or a few sentences if you prefer that method.

If you plan to use multiple datasets, add a few sentences about how you plan to combine these datasets.

In [3]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
%pip install requests tqdm
%pip install pandas
%pip install numpy

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/frozenbabywipes/traffice-volumes-dataset/refs/heads/main/traffic_counts_datasd%20(1).csv', 'filename':'traffic_volumes.csv'},
    { 'url': 'https://seshat.datasd.org/city_owned_properties_leases/city_property_leases_datasd.csv', 'filename':'property-prices.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Requirement already satisfied: requests in ./.conda/lib/python3.11/site-packages (2.34.1)
Requirement already satisfied: tqdm in ./.conda/lib/python3.11/site-packages (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.conda/lib/python3.11/site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.conda/lib/python3.11/site-packages (from requests) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in ./.conda/lib/python3.11/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./.conda/lib/python3.11/site-packages (from requests) (2026.4.22)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in ./.conda/lib/python3.11/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in ./.conda/lib/python3.11/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.conda/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in ./.conda/lib/python3.11/site-packages (2.4.4)
Note: you may need to restart the kernel to use updated packages.

Overall Download Progress:  50%|█████     | 1/2 [00:00<00:00,  6.63it/s]

Successfully downloaded: traffic_volumes.csv

Overall Download Progress: 100%|██████████| 2/2 [00:00<00:00,  3.71it/s]

Successfully downloaded: property-prices.csv

### Traffic Volumes in San Diego

This dataset records vehicle counts on San Diego streets in 24 hr intervals (per day). According to Data San Diego (https://data.sandiego.gov/datasets/traffic-volumes/), the specific block segments seen in the data are representative of a larger segment on the same roadway. 

Metrics:
- street_name / limits: 
    - Stored as strings. The frequency of street observations were dependent on city needs to analyze that given area. 
- total_count 
    - Stored as integers. Total count of vehicles traveling in all directions (north, south, east, west) in 24 hrs. 
- count_date
    - Stored as strings. The date vehicles were counted.

Concerns:
- Some streets may be over or underrepresented which will require additional filtering of data when merging datasets
- Vehicle counts is a vague description. It's unknown if vehicles were large, small, heavy, light, etc. which may affect our hypothesis (e.g. what if all the vehicles recorded were bikes?). Reasonable however, we may assume that a majority of counts were of cars. 
- Vehicle counts were not taken every day. There are gaps in recorded dates which may also leave gaps of observable comparisons between our datasets.

#### Import pandas + numpy + load dataset

In [5]:
import pandas as pd
import numpy as np

df_traf_vol = pd.read_csv('https://raw.githubusercontent.com/frozenbabywipes/traffice-volumes-dataset/refs/heads/main/traffic_counts_datasd%20(1).csv')

df_traf_vol

,id,street_name,limits,northbound_count,southbound_count,eastbound_count,westbound_count,total_count,file_no,date_count
0,01AV018207,01 AV,A ST - ASH ST,18010,NaN,NaN,NaN,18010,0182-07,2007-03-13 00:00:00
1,01AV015210,01 AV,A ST - ASH ST,20060,NaN,NaN,NaN,20060,0152-10,2010-03-18 00:00:00
2,01AV018213,01 AV,A ST - ASH ST,19597,NaN,NaN,NaN,19597,0182-13,2013-03-12 00:00:00
3,01AV007721,01 AV,A ST - ASH ST,10640,NaN,NaN,NaN,10640,0077-21,2021-03-10 00:00:00
4,01AV088812,01 AV,ASH ST - BEECH ST,2298,NaN,NaN,NaN,2298,0888-12,2012-12-11 00:00:00
...,...,...,...,...,...,...,...,...,...,...
13686,ZOOPL009205,ZOO PL,PARK BL - FLORIDA DR,2620,3680.0,NaN,NaN,6300,0092-05,2005-04-07 00:00:00
13687,ZOOPL013708,ZOO PL,PARK BL - FLORIDA DR,4790,4640.0,NaN,NaN,9430,0137-08,2008-03-20 00:00:00
13688,ZOOPL033011,ZOO PL,PARK BL - FLORIDA DR,2425,3170.0,NaN,NaN,5595,0330-11,2014-05-24 00:00:00
13689,ZOOPL112614,ZOO PL,PARK BL - FLORIDA DR,1935,2490.0,NaN,NaN,4425,1126-14,2014-12-16 00:00:00
13690,ZOOPL022018,ZOO PL,PARK BL - FLORIDA DR,3110,3164.0,NaN,NaN,6274,0220-18,2018-04-17 00:00:00

#### Checking shape and columns

In [6]:
print(df_traf_vol.shape)
print(df_traf_vol.columns)

(13691, 10)
Index(['id', 'street_name', 'limits', 'northbound_count', 'southbound_count',
       'eastbound_count', 'westbound_count', 'total_count', 'file_no',
       'date_count'],
      dtype='str')

#### Drop unnecessary columns

In [7]:
df_traf_vol = df_traf_vol.drop(columns=['id','northbound_count', 'southbound_count', 'eastbound_count', 'westbound_count', 'file_no'])

df_traf_vol

      street_name                limits  total_count           date_count
0           01 AV         A ST - ASH ST        18010  2007-03-13 00:00:00
1           01 AV         A ST - ASH ST        20060  2010-03-18 00:00:00
2           01 AV         A ST - ASH ST        19597  2013-03-12 00:00:00
3           01 AV         A ST - ASH ST        10640  2021-03-10 00:00:00
4           01 AV     ASH ST - BEECH ST         2298  2012-12-11 00:00:00
...           ...                   ...          ...                  ...
13686      ZOO PL  PARK BL - FLORIDA DR         6300  2005-04-07 00:00:00
13687      ZOO PL  PARK BL - FLORIDA DR         9430  2008-03-20 00:00:00
13688      ZOO PL  PARK BL - FLORIDA DR         5595  2014-05-24 00:00:00
13689      ZOO PL  PARK BL - FLORIDA DR         4425  2014-12-16 00:00:00
13690      ZOO PL  PARK BL - FLORIDA DR         6274  2018-04-17 00:00:00

[13691 rows x 4 columns]

#### Checking for missing data + Drop rows with any NaNs
- Dropping all observations with any NaN entries as we need data from every column.

In [26]:
df_traf_vol = df_traf_vol.dropna()


# Outputs 2 rows with at least NaNs before removing null
null_rows = df_traf_vol.isnull().any(axis=1).sum()


print(null_rows)

0

#### Exploring data

In [9]:
print('\nUnderstanding data types:')
print(df_traf_vol.dtypes)


print('\nMinimum total count:')
print(df_traf_vol['total_count'].min())


print('\nMaximum total count:')
print(df_traf_vol['total_count'].max())


print('\nOldest date in data:')
print(df_traf_vol['date_count'].min())


print('\nMost recent date in data:')
print(df_traf_vol['date_count'].max())


rows_with_zero = df_traf_vol[df_traf_vol['total_count'] == 0]
count_rows_with_zero = len(rows_with_zero)


print('\nRows that have a total count of 0:')
print(rows_with_zero)


print('\n# of rows that have a total count of 0:')
print(count_rows_with_zero)

Understanding data types:
street_name      str
limits           str
total_count    int64
date_count       str
dtype: object

Minimum total count:
0

Maximum total count:
89090

Oldest date in data:
2005-01-05 00:00:00

Most recent date in data:
2022-11-22 00:00:00

Rows that have a total count of 0:
                 street_name                                limits  \
1204                   55 ST            HARDY AV - CANYON CREST DR
1572   ALLEY S/O EL CAJON BL                         67 ST - 68 ST
1829    AVENIDA PLAYA  PLAYA   PASEO OCASO DR - LA JOLLA SHORES DR
2474               BONAIR ST                 TYRAIN ST - DRAPER AV
2618       BROADWAY BROADWAY                          30 ST - F ST
3728              CHELSEA AV             CRYSTAL DR - SEA RIDGE DR
3731              CHELSEA AV          DOLPHIN PL - CAMINO COSTA PL
3734              CHELSEA ST             SEA RIDGE DR - CHELSEA AV
3941           CLIFFRIDGE AV                N/O GLENBROOK AV -  AV
3953                COAST BL              PROSPECT ST - COAST BL S
3968               COLIMA ST                 BELLEVUE AV - TAFT AV
4047        COLLEGE GROVE DR           54 ST - CAMINITO CHOLLAS ST
5499              FORWARD ST                 BELLEVUE AV - TAFT AV
6459                 HILL ST                 TARENTO DR - MOANA DR
7708           LINDA ROSA AV                MIDWAY ST - FORWARD ST
7808              LOOKOUT DR             SOLEDAD AV - BOULEVARD PL
8391               MIDWAY ST                 BELLEVUE AV - TAFT AV
8725              MISSION BL                   THOMAS AV - REED AV
9284             N HARBOR DR              PACIFIC HY - BROADWAY HY
9727        OLD CARMEL VY RD              SANDOWN WY - MILL CRK RD
9734           OLD MEMORY LN                    60 ST - ROSWELL ST
10533            POMERADO RD         POMERADO CT - PASEO VERANO CT
11083              ROMERO DR               BRODIAEA WY - ROMERO CT
11186             ROSELLE ST                SD 005 ST - DUNHILL ST
11224              RUFFIN RD  CLAIREMONT MESA BL - KEARNY VILLA RD
11422          SAN YSIDRO BL             DAIRY MART RD - HOWARD AV
12235              SUNSET RD             JUAN ST - LA CALLECITA ST
12761          UNIVERSITY AV                      ALAMO DR - 68 ST
12892                UPAS ST                  HERBERT ST - PARK BL
13470             WAVERLY AV             FORWARD ST - BIRD ROCK AV

       total_count           date_count
1204             0  2006-06-21 00:00:00
1572             0  2006-07-11 00:00:00
1829             0  2010-12-08 00:00:00
2474             0  2006-06-20 00:00:00
2618             0  2006-06-28 00:00:00
3728             0  2006-08-02 00:00:00
3731             0  2006-08-02 00:00:00
3734             0  2006-08-02 00:00:00
3941             0  2006-06-20 00:00:00
3953             0  2006-09-12 00:00:00
3968             0  2006-08-02 00:00:00
4047             0  2006-06-20 00:00:00
5499             0  2006-08-02 00:00:00
6459             0  2006-08-08 00:00:00
7708             0  2006-08-02 00:00:00
7808             0  2006-09-12 00:00:00
8391             0  2006-08-02 00:00:00
8725             0  2006-06-20 00:00:00
9284             0  2006-06-21 00:00:00
9727             0  2006-06-20 00:00:00
9734             0  2006-06-21 00:00:00
10533            0  2006-06-20 00:00:00
11083            0  2006-09-12 00:00:00
11186            0  2006-09-12 00:00:00
11224            0  2006-06-20 00:00:00
11422            0  2006-06-19 00:00:00
12235            0  2006-06-28 00:00:00
12761            0  2006-06-21 00:00:00
12892            0  2006-06-20 00:00:00
13470            0  2006-08-02 00:00:00

# of rows that have a total count of 0:
30

#### Removing outliers
- Removing 30 observations that recorded 0 total vehicles within 24 hrs. This data seems unlikely unless there were prolonged street closures.

In [10]:
df_traf_vol = df_traf_vol[df_traf_vol['total_count'] != 0]


# verify that rows with outlier values are dropped
print('\nRows that have a total count of 0:')
print((df_traf_vol['total_count'] == 0).sum())


# checking for new minimum
print('\nNew minimum total count:')
print(df_traf_vol['total_count'].min())


# check how many observations counted 5 vehicles
rows_with_five = df_traf_vol[df_traf_vol['total_count'] == 5]
count_rows_with_five= len(rows_with_five)
print('\n# of rows that have a total count of 5:')
print(count_rows_with_five)
print('\nThis new minimum of 5 total vehicles counted for one day may account for construction of a road so it may be more plausible than a total count of 0')

Rows that have a total count of 0:
0

New minimum total count:
5

# of rows that have a total count of 5:
1

This new minimum of 5 total vehicles counted for one day may account for construction of a road so it may be more plausible than a total count of 0

#### Filtering out irrelevent dates
- We are only looking from January 09, 2017 (most recent oldest date in pothole dataset) to Novemeber 22, 2022 (oldest most recent date from traffic volume dataset)

In [11]:
df_traf_vol = df_traf_vol[df_traf_vol['date_count'] >= '2017-01-09']

# check new oldest date
df_traf_vol['date_count'].min()

'2017-01-11 00:00:00'

#### Clean + Tidy Traffic Volume Dataset

In [12]:
traffic_volume = df_traf_vol

traffic_volume

,street_name,limits,total_count,date_count
3,01 AV,A ST - ASH ST,10640,2021-03-10 00:00:00
14,01 AV,BEECH ST - CEDAR ST,16482,2020-03-12 00:00:00
38,01 AV,JUNIPER ST - KALMIA ST,5842,2022-03-16 00:00:00
43,01 AV,JUNIPER ST - KALMIA ST,5262,2018-03-13 00:00:00
60,01 AV,PENNSYLVANIA AV - ROBINSON AV,7715,2018-03-15 00:00:00
...,...,...,...,...
13675,YERBA STA DR,MESQUITE RD - MONTEZUMA RD,2561,2021-08-04 00:00:00
13678,ZION AV,C LEE AV - ESTRELLA AV,10655,2021-06-15 00:00:00
13684,ZION AV,MISSION GORGE RD - WARING RD,12239,2021-11-10 00:00:00
13685,ZOO PL,PARK BL - FLORIDA DR,5349,2022-04-28 00:00:00
13690,ZOO PL,PARK BL - FLORIDA DR,6274,2018-04-17 00:00:00

### SD County Property Prices

This dataset records information about San Diego City-owned property. Primarily, it provides data about rent amounts, start/end dates, leasees, and the type of properties in San Diego.

Metrics:
- address_zip: 
    - Zip code of the lease
- cost_line_amt_USD: 
    - Amount of lease payments
- effective_date: 
    - Date of lease effective
- sched_termination_date: 
    - Scheduled date for the lease to be terminated

Concerns:
- This dataset doesn't encapsulate all of the properties within San Diego County.
- Given that there are different start/end dates per properties, additional consideration + filtering must be done to decide what properties we want to include in our question's timeframe
- Zip codes + prices may be revealing for certain property types (mostly residential) but we argue that this information is already accessible via sites like Zillow. 

See instructions above for Dataset #1.  Feel free to keep adding as many more datasets as you need.  Put each new dataset in its own section just like these. 

Lastly if you do have multiple datasets, add another section where you demonstrate how you will join, align, cross-reference or whatever to combine data from the different datasets

Please note that you can always keep adding more datasets in the future if these datasets you turn in for the checkpoint aren't sufficient.  The goal here is demonstrate that you can obtain and wrangle data.  You are not tied down to only use what you turn in right now.

#### Import pandas + numpy + dataset upload

In [13]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
import pandas as pd
import numpy as np

prices = pd.read_csv('https://seshat.datasd.org/city_owned_properties_leases/city_property_leases_datasd.csv')
prices

,site_code,lessee_name,lessee_company,lessee_DBA,address_zip,lease_record_type,lease_description,lease_status,lease_location_name,nonprofit_lessee,date_effective,date_sched_termination,rent_code,cost_line_amt_USD
0,A001WR,"NEAL, ROBERT","NEAL, ROBERT",NaN,92065,Lease,AGRICULTURE & CATTLE GRAZING,Held Over,PAMO VALLEY,0.0,4/18/2019,4/17/2022,NaN,NaN
1,A001WR,SAN DIEGUITO RIVER PARK JPA/15,SAN DIEGUITO RIVER PARK JPA,NaN,92025,Permit,MAINTENANCE & RESTORATION,Normal,PAMO VALLEY,0.0,12/1/2016,11/30/2036,NaN,NaN
2,A007WW,PACIFIC TELEPHONE/01,PACIFIC TELEPHONE/01,AT&T,75202-4206,Permit,TELEPHONE CABLE,MTM,"SUTHERLAND DAM, CITY RESIDENCE",0.0,3/12/1974,NaN,NaN,NaN
3,ADMIN,"AG ESSENTIAL HOUSING CA 2, LP","AG ESSENTIAL HOUSING CA 2, LP",NaN,92008,Agreement,OTAY 2ND PIPELINE EASEMENT,MTM,"CHULA VISTA, COUNTY OF SAN DIEGO",0.0,11/4/2021,NaN,NaN,NaN
4,ADMIN,"WESTFIELD CORPORATION, INC.",SPINOSO REAL ESTATE GROUP,NORTH COUNTY FAIR,13212,Agreement,SHOPPING CENTER,Normal,I-15& VIA RANCHO PARKWAY ESCONDIDO,0.0,4/8/1980,6/30/2033,FMD,8333.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,Z715PM,SD METROPOLITAN TRANSIT SYSTEM,SAN DIEGO METROPOLITAN TRANSIT,NaN,92101,Agreement,COMMUNICATIONS EQUIPMENT,Held Over,MOODY CANYON COM CENTER-SAN YSIDRO,0.0,11/1/2014,10/31/2024,FYR,33866.90
812,Z715PM,STATE OF CA/CHP/03,STATE OF CA/CHP/03,DEPT. OF GENERAL SERVICES-DGS,95798-9052,Lease,COMMUNICATIONS FACILITY,Held Over,MOODY CANYON AKA SAN YSIDRO,0.0,3/1/2012,2/28/2022,FQR,9983.09
813,Z715PM,US CUSTOMS & BORDER PROTECTION/05,US CUSTOMS & BORDER PROTECTION,NaN,76040,Lease,TELECOMMUNICATIONS EQUIPMENT,Normal,SAN YSIDRO/ MOODY CANYON,0.0,10/1/2017,9/30/2037,NaN,NaN
814,Z719PM,COUNTY OF SAN DIEGO/12 TIJUANA RIVER PARK,COUNTY OF SAN DIEGO/12,NaN,92123-1666,Joint Powers,MAINTENANCE OF PARK,Held Over,TIJUANA RIVER REGIONAL PARK,0.0,3/4/1996,3/3/2021,NaN,NaN
815,Z728PM,INTERCAM FINANCIAL SERVICES INC,INTERCAM FINANCIAL SERVICES INC,NaN,92173,Permit,PARKING,Normal,ADJACENT 360-399 E. SAN YSIDRO BLVD. SAN DIEGO...,0.0,12/1/2024,11/30/2029,FMD,4748.00

#### Checking Column Names and Shape

In [14]:
print(prices.columns)
print(prices.shape)

Index(['site_code', 'lessee_name', 'lessee_company', 'lessee_DBA',
       'address_zip', 'lease_record_type', 'lease_description', 'lease_status',
       'lease_location_name', 'nonprofit_lessee', 'date_effective',
       'date_sched_termination', 'rent_code', 'cost_line_amt_USD'],
      dtype='str')
(816, 14)

#### Drop Unneeded Columns

In [15]:
prices = prices.drop(columns=['lessee_name', 'lessee_company', 'lessee_DBA'])

#### Drop Rows with Data Missing Under Cost Column

In [16]:
prices = prices.dropna(subset=['cost_line_amt_USD'])

prices

,site_code,address_zip,lease_record_type,lease_description,lease_status,lease_location_name,nonprofit_lessee,date_effective,date_sched_termination,rent_code,cost_line_amt_USD
4,ADMIN,13212,Agreement,SHOPPING CENTER,Normal,I-15& VIA RANCHO PARKWAY ESCONDIDO,0.0,4/8/1980,6/30/2033,FMD,8333.33
5,ADMIN,92101,Lease,TRANSITIONAL HOUSING 5550,Normal,"FRIARS RD, MISSION VALLEY",1.0,5/1/2026,4/30/2036,FMD,402.00
6,BLDG,92103-1946,Lease,CHILD CARE CENTER,MTM,1425 WASHINGTON PL SD CA 92103,0.0,3/1/2002,2/29/2012,FMD,1424.44
8,C601WR,92025-2301,Lease,PEDESTRIAN BRIDGE,Normal,"HODGES RESERVOIR, WEST OF I-15",0.0,11/1/2007,10/31/2032,FYD,525.40
12,C701P2,92110,Permit,OPERATION AND MAINTENANCE OF STATE HISTORICAL ...,Held Over,POR RHO SAN BERNARDO,0.0,4/1/1988,3/31/1993,FYD,100.00
...,...,...,...,...,...,...,...,...,...,...,...
809,Z706RS,NaN,Permit,Expense to Park and Rec paid interfund to Water,MTM,Sycamore Rd - San Ysidro Park,0.0,12/18/1973,NaN,FYD,4100.00
810,Z706RS,92101,Lease,SPORTS FIELD,MTM,"SAN YSIDRO, LARSEN FIELD",0.0,12/18/1973,NaN,FYD,4100.00
811,Z715PM,92101,Agreement,COMMUNICATIONS EQUIPMENT,Held Over,MOODY CANYON COM CENTER-SAN YSIDRO,0.0,11/1/2014,10/31/2024,FYR,33866.90
812,Z715PM,95798-9052,Lease,COMMUNICATIONS FACILITY,Held Over,MOODY CANYON AKA SAN YSIDRO,0.0,3/1/2012,2/28/2022,FQR,9983.09
815,Z728PM,92173,Permit,PARKING,Normal,ADJACENT 360-399 E. SAN YSIDRO BLVD. SAN DIEGO...,0.0,12/1/2024,11/30/2029,FMD,4748.00

#### Keep Data within a Timeframe

In [17]:
prices['date_effective'] = pd.to_datetime(prices['date_effective'], errors='coerce')

prices = prices[prices['date_effective'].between('2017-01-09', '2026-05-12')]

prices['date_effective'].min()

print(prices)

    site_code address_zip lease_record_type  \
5       ADMIN       92101             Lease
15     C701WW       92025             Lease
21     C701WW  92105-1607         Agreement
57     C701WW  92261-4563             Lease
70       CITY       92127             Lease
..        ...         ...               ...
735    Y802PA       90025         Agreement
803    Z702PM       92173         Agreement
805    Z702PM       92868         Agreement
806    Z702PM       92173         Agreement
815    Z728PM       92173            Permit

                                     lease_description lease_status  \
5                            TRANSITIONAL HOUSING 5550       Normal
15                            ORGANIC ROW CROP FARMING    Held Over
21                                         FRUIT TREES       Normal
57                                  GROW & HARVEST SOD       Normal
70   Renting warehouse for Police property and evid...     Extended
..                                                 ...          ...
735             RENT OFFSET AGREEMENT, PHASE 2 PARCELS       Normal
803                                       OFFICE SPACE       Normal
805                                         OFFICE USE       Normal
806                                         OFFICE USE          MTM
815                                            PARKING       Normal

                                   lease_location_name  nonprofit_lessee  \
5                            FRIARS RD, MISSION VALLEY               1.0
15                      20505 SAN PASQUALVALLEY RD SD                0.0
21   21250 & 24330 SAN PASQUAL RD. ESCONDIDO, CA 92...               0.0
57                                  SAN PASQUAL VALLEY               0.0
70                                  Jerome’s Warehouse               0.0
..                                                 ...               ...
735                                        BROWN FIELD               0.0
803                663 E. SAN YSIDRO BLVD. SD CA 92173               0.0
805   663 E. SAN YSIDRO BLVD SUITES 3, 4, 5A, 5B AND 6               0.0
806       663 E. SAN YSIDRO  BLVD. SAN YSIDRO CA 92173               0.0
815  ADJACENT 360-399 E. SAN YSIDRO BLVD. SAN DIEGO...               0.0

    date_effective date_sched_termination rent_code  cost_line_amt_USD
5       2026-05-01              4/30/2036       FMD             402.00
15      2023-03-01              2/28/2026       FQD           24720.00
21      2025-06-06               6/5/2027       FMD             816.67
57      2020-07-01              6/30/2050       PYR          249780.00
70      2022-01-01             12/31/2027       FMD           14529.00
..             ...                    ...       ...                ...
735     2024-12-29             12/28/2029       FMD           20833.34
803     2025-06-25              6/24/2028       FYD            1200.00
805     2024-03-01             11/27/2026       FMD            2264.92
806     2024-03-11              3/10/2027       FMD             402.29
815     2024-12-01             11/30/2029       FMD            4748.00

[300 rows x 11 columns]

In [27]:
#### Drop Rows without Zip Code

In [19]:
prices = prices.dropna(subset=['address_zip'])

prices

,site_code,address_zip,lease_record_type,lease_description,lease_status,lease_location_name,nonprofit_lessee,date_effective,date_sched_termination,rent_code,cost_line_amt_USD
5,ADMIN,92101,Lease,TRANSITIONAL HOUSING 5550,Normal,"FRIARS RD, MISSION VALLEY",1.0,2026-05-01,4/30/2036,FMD,402.00
15,C701WW,92025,Lease,ORGANIC ROW CROP FARMING,Held Over,20505 SAN PASQUALVALLEY RD SD,0.0,2023-03-01,2/28/2026,FQD,24720.00
21,C701WW,92105-1607,Agreement,FRUIT TREES,Normal,"21250 & 24330 SAN PASQUAL RD. ESCONDIDO, CA 92...",0.0,2025-06-06,6/5/2027,FMD,816.67
57,C701WW,92261-4563,Lease,GROW & HARVEST SOD,Normal,SAN PASQUAL VALLEY,0.0,2020-07-01,6/30/2050,PYR,249780.00
70,CITY,92127,Lease,Renting warehouse for Police property and evid...,Extended,Jerome’s Warehouse,0.0,2022-01-01,12/31/2027,FMD,14529.00
...,...,...,...,...,...,...,...,...,...,...,...
735,Y802PA,90025,Agreement,"RENT OFFSET AGREEMENT, PHASE 2 PARCELS",Normal,BROWN FIELD,0.0,2024-12-29,12/28/2029,FMD,20833.34
803,Z702PM,92173,Agreement,OFFICE SPACE,Normal,663 E. SAN YSIDRO BLVD. SD CA 92173,0.0,2025-06-25,6/24/2028,FYD,1200.00
805,Z702PM,92868,Agreement,OFFICE USE,Normal,"663 E. SAN YSIDRO BLVD SUITES 3, 4, 5A, 5B AND 6",0.0,2024-03-01,11/27/2026,FMD,2264.92
806,Z702PM,92173,Agreement,OFFICE USE,MTM,663 E. SAN YSIDRO BLVD. SAN YSIDRO CA 92173,0.0,2024-03-11,3/10/2027,FMD,402.29
815,Z728PM,92173,Permit,PARKING,Normal,ADJACENT 360-399 E. SAN YSIDRO BLVD. SAN DIEGO...,0.0,2024-12-01,11/30/2029,FMD,4748.00

#### Sort Data by Zip Code

In [20]:
prices = prices.sort_values(by='address_zip')

prices

,site_code,address_zip,lease_record_type,lease_description,lease_status,lease_location_name,nonprofit_lessee,date_effective,date_sched_termination,rent_code,cost_line_amt_USD
661,STREET,07921,Permit,COMMUNICATIONS EQUIPMENT,Normal,VARIOUS POLES,0.0,2021-02-09,2/8/2031,FYD,2300.00
209,L301LB,07921,Lease,COMMUNICATIONS EQUIPMENT,Normal,"4155 GOVERNOR DR. SD, CA 92122",0.0,2019-03-01,2/28/2029,FYD,49801.30
662,STREET,07921,Permit,COMUNICATIONS EQUIPMENT,Normal,VARIOUS POLES,0.0,2021-02-23,2/22/2031,FYD,2000.00
581,S203WM,07921,Lease,COMMUNICATIONS EQUIPMENT,Normal,"209 CATALINA BLVD SD, CA",0.0,2018-11-01,10/31/2028,FYD,53090.03
660,STREET,07921,Permit,COMMUNICATIONS/TELECOM,Normal,VARIOUS POLES,0.0,2021-01-15,1/14/2031,FYD,2100.00
...,...,...,...,...,...,...,...,...,...,...,...
333,N508PA,97759,Lease,HANGAR,Normal,"3750 JOHN J MONTGOMERY DR SD, CA 92123",0.0,2020-02-26,6/30/2032,FMD,101.20
719,Y603RD,98006,License,COMMUNICATIONS EQUIPMENT,Held Over,"3020 CORONADO AVE SD, CA 92154",0.0,2024-02-22,2/21/2026,FYD,48141.39
702,T706WM,98006,Lease,COMMUNICATIONS EQUIPMENT,Normal,1513 STATTON CT.,0.0,2019-06-01,5/31/2029,FYD,51295.11
419,O802RD,98006,Lease,COMMUNICATIONS EQUIPMENT,Normal,6445 LAKE BADIN AVE.,0.0,2017-11-01,10/31/2027,FYD,50038.74
134,E901PM,98115-6349,Permit,RADIO TRANSMITTING/RECEIVING,Held Over,MT. WOODSON,0.0,2018-03-01,2/28/2021,FMR,926.09

### Pothole Requests

Descriptive paragraph + metrics + concerts

#### Load dataset

In [21]:
df_potholes = pd.read_csv('https://raw.githubusercontent.com/frozenbabywipes/traffice-volumes-dataset/refs/heads/main/get_it_done_pothole_requests_datasd%20(1).csv')


df_potholes

,service_request_id,service_request_parent_id,sap_notification_number,date_requested,case_age_days,case_record_type,service_name,service_name_detail,date_closed,status,...,zipcode,council_district,comm_plan_code,comm_plan_name,park_name,case_origin,referred,iamfloc,floc,public_description
0,131444,NaN,4.030010e+10,2017-01-09T16:22:00,1738.0,TSW,Pothole,NaN,2021-10-13,Closed,...,92110.0,2.0,30.0,Peninsula,NaN,Web,NaN,SS-003583-PV1,SS-003583-PV1,"the entire street is a pothole, and has been f..."
1,2403110,2401124.0,NaN,2018-09-18T14:39:00,930.0,TSW,Pothole,NaN,2021-04-05,Closed,...,92120.0,9.0,38.0,College Area,NaN,Phone,NaN,SS-007582-PV1,SS-007582-PV1,TWO POTHOLES COLLEGE AV N BETWEEN I 8 & CAPRI...
2,2403347,2403345.0,NaN,2018-09-18T18:27:00,1130.0,TSW,Pothole,NaN,2021-10-22,Closed,...,92139.0,4.0,44.0,Skyline-Paradise Hills,NaN,Web,NaN,SS-024890-PV1,SS-024890-PV1,I have submitted multiple requests! Potholes d...
3,2406519,2401124.0,NaN,2018-09-22T10:54:00,926.0,TSW,Pothole,NaN,2021-04-05,Closed,...,92120.0,7.0,20.0,Navajo,NaN,Mobile,NaN,SS-007582-PV1,SS-007582-PV1,Southbound Lanes of College approaching I-8 we...
4,2418337,2418290.0,NaN,2018-10-08T14:15:00,1676.0,TSW,Pothole,NaN,2023-05-11,Closed,...,92037.0,1.0,10.0,La Jolla,NaN,Web,NaN,SS-010104-PV1,SS-010104-PV1,This street also has many grooves and potholes...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100575,5715656,NaN,4.030110e+10,2026-05-12T18:23:00,1.0,TSW,Pothole,NaN,NaN,In Process,...,92037.0,1.0,10.0,LA JOLLA,NaN,Mobile,NaN,SS-010096-PV1,SS-010096-PV1,Pothole || LOCATION: El Paseo Grande & Valleci...
100576,5715691,NaN,4.030110e+10,2026-05-12T18:57:00,1.0,TSW,Pothole,NaN,NaN,In Process,...,92136.0,8.0,2.0,BARRIO LOGAN,NaN,Mobile,NaN,SS-029375-PV1,SS-029375-PV1,Pot holes on 32nd street between fright train ...
100577,5715763,NaN,NaN,2026-05-12T20:16:00,0.0,TSW,Pothole,NaN,2026-05-12,Closed,...,92126.0,6.0,15.0,MIRA MESA,NaN,Web,NaN,SS-002584-PV1,SS-002584-PV1,"the street is getting worse for a few years, h..."
100578,5715810,NaN,4.030110e+10,2026-05-12T22:00:00,1.0,TSW,Pothole,NaN,NaN,In Process,...,92173.0,8.0,33.0,SAN YSIDRO,NaN,Mobile,NaN,SS-029779-PV1,SS-029779-PV1,Pot hole || LOCATION: Via San Ysidro and Camin...
100579,5715813,NaN,NaN,2026-05-12T22:12:00,0.0,TSW,Pothole,NaN,2026-05-12,Closed,...,92103.0,3.0,42.0,UPTOWN,NaN,Mobile,NaN,SS-027520-PV1,SS-027520-PV1,Whole street ripped up between normal and 10th...

#### Checking shape and columns

In [22]:
print(df_potholes.shape)
print(df_potholes.columns)

(100580, 23)
Index(['service_request_id', 'service_request_parent_id',
       'sap_notification_number', 'date_requested', 'case_age_days',
       'case_record_type', 'service_name', 'service_name_detail',
       'date_closed', 'status', 'lat', 'lng', 'street_address', 'zipcode',
       'council_district', 'comm_plan_code', 'comm_plan_name', 'park_name',
       'case_origin', 'referred', 'iamfloc', 'floc', 'public_description'],
      dtype='str')

In [23]:
df_potholes = df_potholes.drop(columns=['service_request_id', 'service_request_parent_id', 'sap_notification_number', 'case_age_days', 'case_record_type', 'service_name_detail', 'date_closed', 'lat', 'lng', 'council_district', 'comm_plan_code', 'comm_plan_name', 'park_name',
       'case_origin', 'referred', 'iamfloc', 'floc', 'public_description'])

df_potholes

,date_requested,service_name,status,street_address,zipcode
0,2017-01-09T16:22:00,Pothole,Closed,"2869 Barnard Street, San Diego, CA, United States",92110.0
1,2018-09-18T14:39:00,Pothole,Closed,"COLLEGE AV, 92115",92120.0
2,2018-09-18T18:27:00,Pothole,Closed,"1847 Sherbrooke St, San Diego, CA 92139, USA",92139.0
3,2018-09-22T10:54:00,Pothole,Closed,"5661 College Ave, San Diego, CA 92120, USA",92120.0
4,2018-10-08T14:15:00,Pothole,Closed,"1515 El Paso Real, La Jolla, CA 92037, USA",92037.0
...,...,...,...,...,...
100575,2026-05-12T18:23:00,Pothole,In Process,8110 El Paseo Grande,92037.0
100576,2026-05-12T18:57:00,Pothole,In Process,S 32nd St,92136.0
100577,2026-05-12T20:16:00,Pothole,Closed,"Ara Pl, San Diego, CA 92126, USA",92126.0
100578,2026-05-12T22:00:00,Pothole,In Process,283?299 E Calle Primera,92173.0
100579,2026-05-12T22:12:00,Pothole,Closed,Vermont St,92103.0

#### Checking for missing data

In [24]:
# Outputs 908 rows (899 with NaN zipcodes and 9 with NaN addresses) before removing null
null_rows = df_potholes.isnull().any(axis=1).sum()

print(df_potholes.isnull().sum())
print(null_rows)

print('\nWhat do null zips look like')
zip_null_ex = df_potholes[df_potholes['zipcode'].isnull()].head()
print(zip_null_ex)

print('\nWhat do null addresses look like')
address_null_ex = df_potholes[df_potholes['street_address'].isnull()].head()
print(address_null_ex)

date_requested      0
service_name        0
status              0
street_address      9
zipcode           899
dtype: int64
908

What do null zips look like
           date_requested service_name  status  \
434   2020-12-29T16:32:00      Pothole  Closed
714   2021-01-07T17:29:00      Pothole  Closed
1568  2021-02-02T10:53:00      Pothole  Closed
1911  2021-02-10T10:01:00      Pothole  Closed
2285  2021-02-18T14:15:00      Pothole  Closed

                                      street_address  zipcode
434   8333 Calle Del Cielo, San Diego, Ca 92037, Usa      NaN
714       3023 Lincoln Ave, San Diego, CA 92104, USA      NaN
1568   9878 Mira Mesa Blvd, San Diego, Ca 92131, Usa      NaN
1911                             6430 INYO ST, 92139      NaN
2285    Camino De La Reina, San Diego, CA 92108, USA      NaN

What do null addresses look like
            date_requested service_name  status street_address  zipcode
97     2019-11-26T06:28:00      Pothole  Closed            NaN  92131.0
161    2020-03-21T14:49:00      Pothole  Closed            NaN  92129.0
1952   2021-02-11T08:13:00      Pothole  Closed            NaN  92093.0
6020   2021-04-24T18:09:00      Pothole  Closed            NaN  92116.0
37862  2023-02-13T12:35:00      Pothole  Closed            NaN  92113.0

#### Drop rows with any NaNs
- Dropping all observations with empty address or zip as we potentially need address and zip code data.

In [25]:
df_potholes = df_potholes.dropna()

null_rows = df_potholes.isnull().any(axis=1).sum()

print(null_rows)

0

#### Exploring data

In [ ]:
print('\nUnderstanding data types:')
print(df_potholes.dtypes)

#make sure uniform datetime format
df_potholes['date_requested'] = pd.to_datetime(df_potholes['date_requested'])

print('\nOldest date in data:')
print(df_potholes['date_requested'].min())

print('\nMost recent date in data:')
print(df_potholes['date_requested'].max())

print('\nAre there any requests that are not potholes?')
print(df_potholes['service_name'].unique())

Understanding data types:
date_requested        str
service_name          str
status                str
street_address        str
zipcode           float64
dtype: object

Oldest date in data:
2017-01-09 16:22:00

Most recent date in data:
2026-05-12 22:12:00

Are there any requests that are not potholes?
<StringArray>
['Pothole']
Length: 1, dtype: str

#### Filtering out irrelevent dates
- We are only looking from January 09, 2017 (most recent oldest date in pothole dataset) to Novemeber 22, 2022 (oldest most recent date from traffic volume dataset)

In [ ]:
df_potholes = df_potholes[df_potholes['date_requested'] <= '2022-11-22']

# check new most recent date
df_potholes['date_requested'].max()

Timestamp('2022-11-21 20:02:00')

#### Clean + Tidy Pothole Dataset

In [ ]:
potholes = df_potholes

potholes

,date_requested,service_name,status,street_address,zipcode
0,2017-01-09 16:22:00,Pothole,Closed,"2869 Barnard Street, San Diego, CA, United States",92110.0
1,2018-09-18 14:39:00,Pothole,Closed,"COLLEGE AV, 92115",92120.0
2,2018-09-18 18:27:00,Pothole,Closed,"1847 Sherbrooke St, San Diego, CA 92139, USA",92139.0
3,2018-09-22 10:54:00,Pothole,Closed,"5661 College Ave, San Diego, CA 92120, USA",92120.0
4,2018-10-08 14:15:00,Pothole,Closed,"1515 El Paso Real, La Jolla, CA 92037, USA",92037.0
...,...,...,...,...,...
27283,2022-11-21 17:52:00,Pothole,Closed,2800 Torrey Pines Scenic Drive,92037.0
27284,2022-11-21 19:04:00,Pothole,Closed,"Navajo Rd, San Diego, CA, USA",92119.0
27285,2022-11-21 19:19:00,Pothole,Closed,"8856 Shellback Way, La Jolla, CA 92037, USA",92093.0
27286,2022-11-21 20:02:00,Pothole,Closed,7736 Flanders Dr,92126.0
27287,2022-11-21 20:02:00,Pothole,Closed,"6898-6670 Balboa Ave, San Diego, CA 92117, USA",92117.0

### Combining Lease and Pothole

#### Keeping Residential Leases

In [ ]:
prices['lease_description'].unique()

<StringArray>
[       'COMMUNICATIONS EQUIPMENT',         'COMUNICATIONS EQUIPMENT',
          'COMMUNICATIONS/TELECOM',    'TELECOMMUNICATIONS EQUIPMENT',
         'COMMUNICATION EQUIPMENT',         'COMMUNICATIONS FACILITY',
                'TELECOM FACILITY', 'COMMUNICATIONS TELECOM FACILITY',
    'OPTICAL REPEATERS & ANTENNAS',    'HOTEL, SPA, RESTAURANT, DOCK',
 ...
                         'PARKING',                      'OFFICE USE',
     'MOBILE HOT DOG VENDING CART',       'Flattop West 3F Hangar 5B',
              'GROW & HARVEST SOD',                     'AGRICULTURE',
      'ABOVE GROUND PROPANE TANKS',                    'AUTO PARKING',
       'COMMUNICATIONS EQUIPMENT ',    'RADIO TRANSMITTING/RECEIVING']
Length: 154, dtype: str

In [ ]:
prices = prices[
    prices['lease_description'].str.contains(
        'RESIDENTIAL|RESIDENCE|APARTMENT|HOUSING|RENT',
        case=False,
        na=False
    )
]
print(prices)

    site_code address_zip lease_record_type  \
191    J603WR       66223            Permit
733    Y802PA       90025         Agreement
5       ADMIN       92101             Lease
78       CITY  92101-1507             Lease
475    Q309PM       92110             Lease
407    O206PM  92111-1209             Lease
478    Q319PM  92111-1209             Lease
479    Q319PM  92111-1209             Lease
604    S511PM  92114-4213             Lease
347    N508PA       92123         Agreement
70       CITY       92127             Lease
724    Y802PA       92154             Lease
725    Y802PA       92154             Lease

                                     lease_description lease_status  \
191          BOAT RENTAL, MERCHANDISE & PERMIT SALES.        Normal
733             RENT OFFSET AGREEMENT, PHASE 2 PARCELS       Normal
5                            TRANSITIONAL HOUSING 5550       Normal
78                          TEMPORARY HOUSING SHELTERS     Extended
475                                         APARTMENTS       Normal
407                                         APARTMENTS       Normal
478                                         APARTMENTS       Normal
479                             RESIDENTIAL APARTMENTS       Normal
604                                            HOUSING    Held Over
347        1000G CAPACITY FUEL BOWSER RENTAL AGREEMENT       Normal
70   Renting warehouse for Police property and evid...     Extended
724  SALE, RENTALS, SERVICING AND REPAIRS OF AIRCRA...       Normal
725  Sales, rentals, servicing, and repairs of airc...       Normal

                   lease_location_name  nonprofit_lessee date_effective  \
191            VARIOUS CITY RESERVOIRS               0.0     2018-03-01
733                        BROWN FIELD               0.0     2024-12-29
5            FRIARS RD, MISSION VALLEY               1.0     2026-05-01
78                   1710 IMPERIAL AVE               0.0     2019-04-01
475     3889 MIDWAY DR SAN DIEGO 92110               0.0     2017-04-01
407  2150 P.B. DRIVE & 2151 OLIVER AVE               0.0     2022-04-07
478             SPORTS ARENA & HANCOCK               0.0     2022-04-07
479       4040 HANCOCK ST. SD CA 92110               0.0     2022-04-07
604                        904 33rd ST               0.0     2022-04-01
347      3753 JOHN J. MONTGOMERY DRIVE               0.0     2024-10-25
70                  Jerome’s Warehouse               0.0     2022-01-01
724            1424 CONTINENTAL STREET               0.0     2024-04-10
725            1424 Continental Street               0.0     2024-04-10

    date_sched_termination rent_code  cost_line_amt_USD
191              2/28/2038       PMR            5239.38
733             12/28/2029       FMD           20833.34
5                4/30/2036       FMD             402.00
78               6/30/2026       FMD            5464.00
475              3/31/2077       PMR           32586.80
407              4/30/2072       PMR           11078.00
478              4/30/2072       PMR           14857.00
479              4/30/2072       PMR           14079.00
604              3/31/2025       FQD             280.00
347             10/24/2027       FMD             480.00
70              12/31/2027       FMD           14529.00
724             11/30/2033       FMD            3627.29
725             11/30/2041       FMD           17367.00

#### Combining the datasets by matching location

In [ ]:
prices['address_zip'] = prices['address_zip'].astype(str)
potholes['address_zip'] = potholes['address_zip'].astype(str)

potholes['address_zip'] = potholes['address_zip'].str.replace(r'\.0$', '', regex=True)

In [ ]:
potholes = potholes.rename(columns={
    'zipcode': 'address_zip'
})

location_match = prices.merge(potholes, on='address_zip', how='inner')

location_match

,site_code,address_zip,lease_record_type,lease_description,lease_status,lease_location_name,nonprofit_lessee,date_effective,date_sched_termination,rent_code,cost_line_amt_USD,date_requested,service_name,status,street_address
0,ADMIN,92101,Lease,TRANSITIONAL HOUSING 5550,Normal,"FRIARS RD, MISSION VALLEY",1.0,2026-05-01,4/30/2036,FMD,402.0,2019-03-28 16:52:00,Pothole,Closed,"945 Broadway, San Diego, CA 92101, USA"
1,ADMIN,92101,Lease,TRANSITIONAL HOUSING 5550,Normal,"FRIARS RD, MISSION VALLEY",1.0,2026-05-01,4/30/2036,FMD,402.0,2019-04-11 07:34:00,Pothole,Closed,1666 First Ave
2,ADMIN,92101,Lease,TRANSITIONAL HOUSING 5550,Normal,"FRIARS RD, MISSION VALLEY",1.0,2026-05-01,4/30/2036,FMD,402.0,2019-12-21 11:00:00,Pothole,Closed,2464 Brant St
3,ADMIN,92101,Lease,TRANSITIONAL HOUSING 5550,Normal,"FRIARS RD, MISSION VALLEY",1.0,2026-05-01,4/30/2036,FMD,402.0,2020-01-05 09:42:00,Pothole,Closed,1900 PARK BL
4,ADMIN,92101,Lease,TRANSITIONAL HOUSING 5550,Normal,"FRIARS RD, MISSION VALLEY",1.0,2026-05-01,4/30/2036,FMD,402.0,2020-02-27 18:59:00,Pothole,Closed,1600 RUSS BL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4491,Y802PA,92154,Lease,"Sales, rentals, servicing, and repairs of airc...",Normal,1424 Continental Street,0.0,2024-04-10,11/30/2041,FMD,17367.0,2022-11-19 16:08:00,Pothole,Closed,525 Saturn Blvd
4492,Y802PA,92154,Lease,"Sales, rentals, servicing, and repairs of airc...",Normal,1424 Continental Street,0.0,2024-04-10,11/30/2041,FMD,17367.0,2022-11-20 07:15:00,Pothole,Closed,576 Saturn Boulevard
4493,Y802PA,92154,Lease,"Sales, rentals, servicing, and repairs of airc...",Normal,1424 Continental Street,0.0,2024-04-10,11/30/2041,FMD,17367.0,2022-11-21 14:13:00,Pothole,Closed,"2295 PALM AVE, 92154"
4494,Y802PA,92154,Lease,"Sales, rentals, servicing, and repairs of airc...",Normal,1424 Continental Street,0.0,2024-04-10,11/30/2041,FMD,17367.0,2022-11-21 15:27:00,Pothole,Closed,"Coronado Ave & Atwater St, San Diego, CA 92154..."
4495,Y802PA,92154,Lease,"Sales, rentals, servicing, and repairs of airc...",Normal,1424 Continental Street,0.0,2024-04-10,11/30/2041,FMD,17367.0,2022-11-21 15:28:00,Pothole,Closed,"Elm Ave & Granger St, San Diego, CA 92154, USA"

#### Matching Pothole Dates to Lease

In [ ]:
date_match = location_match[
    (location_match['date_requested'] >= location_match['date_effective']) &
    (location_match['date_requested'] <= location_match['date_sched_termination'])
]

date_match

,site_code,address_zip,lease_record_type,lease_description,lease_status,lease_location_name,nonprofit_lessee,date_effective,date_sched_termination,rent_code,cost_line_amt_USD,date_requested,service_name,status,street_address
1234,Q309PM,92110,Lease,APARTMENTS,Normal,3889 MIDWAY DR SAN DIEGO 92110,0.0,2017-04-01,3/31/2077,PMR,32586.8,2019-02-04 14:37:00,Pothole,Closed,"2336 Cowley Way, San Diego, CA 92110, USA"
1235,Q309PM,92110,Lease,APARTMENTS,Normal,3889 MIDWAY DR SAN DIEGO 92110,0.0,2017-04-01,3/31/2077,PMR,32586.8,2019-02-26 14:48:00,Pothole,Closed,"3146B Sports Arena Blvd, San Diego, CA 92110, USA"
1236,Q309PM,92110,Lease,APARTMENTS,Normal,3889 MIDWAY DR SAN DIEGO 92110,0.0,2017-04-01,3/31/2077,PMR,32586.8,2019-03-25 14:58:00,Pothole,Closed,"4129 Sports Arena Blvd, San Diego, CA 92110, USA"
1237,Q309PM,92110,Lease,APARTMENTS,Normal,3889 MIDWAY DR SAN DIEGO 92110,0.0,2017-04-01,3/31/2077,PMR,32586.8,2019-06-03 15:28:00,Pothole,Closed,4920 Milton St
1238,Q309PM,92110,Lease,APARTMENTS,Normal,3889 MIDWAY DR SAN DIEGO 92110,0.0,2017-04-01,3/31/2077,PMR,32586.8,2019-06-20 07:06:00,Pothole,Closed,"2681 Presidio Dr, San Diego, CA 92108, USA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3101,CITY,92127,Lease,Renting warehouse for Police property and evid...,Extended,Jerome’s Warehouse,0.0,2022-01-01,12/31/2027,FMD,14529.0,2022-10-12 11:58:00,Pothole,Closed,"Camino del Norte, San Diego, CA, USA"
3102,CITY,92127,Lease,Renting warehouse for Police property and evid...,Extended,Jerome’s Warehouse,0.0,2022-01-01,12/31/2027,FMD,14529.0,2022-10-18 18:15:00,Pothole,Closed,14203 Caminito Lazanja
3103,CITY,92127,Lease,Renting warehouse for Police property and evid...,Extended,Jerome’s Warehouse,0.0,2022-01-01,12/31/2027,FMD,14529.0,2022-10-21 15:34:00,Pothole,Closed,11555 Rancho Bernardo Road
3104,CITY,92127,Lease,Renting warehouse for Police property and evid...,Extended,Jerome’s Warehouse,0.0,2022-01-01,12/31/2027,FMD,14529.0,2022-10-25 05:22:00,Pothole,Closed,"11245 W Bernardo Ct, San Diego, CA 92127, USA"
3105,CITY,92127,Lease,Renting warehouse for Police property and evid...,Extended,Jerome’s Warehouse,0.0,2022-01-01,12/31/2027,FMD,14529.0,2022-10-31 09:25:00,Pothole,Closed,"17199 Via Del Campo, San Diego, CA 92127, USA"

### Seeing the Pothole Request Count per Lease

In [ ]:
date_match['pothole_count'] = 1
combined_lease_pothole = (
    date_match
    .groupby(['site_code', 'address_zip', 'cost_line_amt_USD'])['pothole_count']
    .sum()
    .reset_index()
)

combined_lease_pothole

  site_code address_zip  cost_line_amt_USD  pothole_count
0      CITY       92127            14529.0             80
1    Q309PM       92110            32586.8           1006

## Ethics

### A. Data Collection

[] **A.1 Informed consent**: If there are human subjects, have they given informed consent, where subjects affirmatively opt-in and have a clear understanding of the data uses to which they consent? 

- N/A

[X] **A.2 Collection bias**: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those?

- One source of bias is that some buildings will be missing because they are not owned by the city of San Diego County. 

[X] **A.3 Limit PII exposure**: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?

- The dataset for the city-owned properties is public information that’s readily available. The dataset will be further wrangled to remove any personally identifiable information and only include relevant information. 

[X] **A.4 Downstream bias mitigation**: Have we considered ways to enable testing downstream results for biased outcomes (e.g., collecting data on protected group status like race or gender)?

- Accessing the data of the city-owned properties is public, so data doesn’t include race or gender but it will have a more biased outcome on the lease owners to be a majority of individuals who have wealthier status, by the city, or companies. Other biases can include specific neighborhoods/areas of the district on wealth gaps but not particularly on data itself. 

### B. Data Storage

[X] **B.1 Data security**: Do we have a plan to protect and secure data (e.g., encryption at rest and in transit, access controls on internal users and third parties, access logs, and up-to-date software)?

- Since we’re looking into city-owned properties whether it is public or private that extend from the 1970s to 2026, San Diego county data is constantly up to date on the county website.  But potential cases are the data not having every exact instance of each property as the cost of living in San Diego is increasing. There can also be data leaks for traffic volumes which can lead to misleading numbers or skews within the different north, east, west, and south bound traffic volume numbers. 

[X] **B.2 Right to be forgotten**: Do we have a mechanism through which an individual can request their personal information be removed?

- For traffic volumes, data is pretty vague so there isn’t a way for an individual to request personal information on traffic. As for properties in the city, there are ways to remove personal information but difficulties on removing company or management owned properties that house rentals or subleases might request to remove, this would lead to the individual consulting with company or management in order to request the removal. 

[X] **B.3 Data retention plan**: Is there a schedule or plan to delete the data after it is no longer needed?

- There isn’t a schedule or plan to delete data after it is no longer needed due to constant observation on changes of numbers of potholes increasing or decreasing and older data including costs of lease as a way to continue experimenting. 

### C. Analysis

[X] **C.1 Missing perspectives**: Have we sought to address blindspots in the analysis through engagement with relevant stakeholders (e.g., checking assumptions and discussing implications with affected communities and subject matter experts)?

-  We’re looking at city-owned properties, which would be missing residential properties. To simulate the residential area, we will be looking at properties pertaining to house rentals and subleases. This won’t be able to encapsulate the entirety of a residential areas, but it’s the best case scenario with the public data available to us.

[X] **C.2 Dataset bias**: Have we examined the data for possible sources of bias and taken steps to mitigate or address these biases (e.g., stereotype perpetuation, confirmation bias, imbalanced classes, or omitted confounding variables)?

- The city property values dataset looks over all types of buildings within the San Diego county, ranging from different occupation durations. The data will be narrowed down into housing only based on their definition, house rental, and subleasing. We do acknowledge this doesn’t include any houses bought by people, and will include a statement to this. The traffic pattern also overlooks all of San Diego county. Some parts of San Diego will be busier than others, so we will take into account the total count of traffic and the location of traffic.  

[X] **C.3 Honest representation**: Are our visualizations, summary statistics, and reports designed to honestly represent the underlying data?

- Our visualizations and summaries will accurately represent the underlying data because we won’t manipulate the data such that it would be changed or skewed. We also won’t leave any data out so that we only keep data we favor or that favors one side. Nothing will be selective as all relevant data will be included and only columns of unnecessary variables will be left out. We will also evaluate if our datasets are limited and only represent a subset of potholes and leases. To ensure accuracy, we will look for repeated pothole reports, lease inactivity via start dates, and inaccurate reports. We would also like to emphasize that we are predicting correlation rather than causation, as we are only observing datasets instead of doing a field experiment. 

[X] **C.4 Privacy in analysis**: Have we ensured that data with PII are not used or displayed unless necessary for the analysis?

- We ensured privacy because our data includes no personal information to the lease buyers and the pothole reporters. If there are names, we will remove that column. This is also because there are only some variables we are interested in such as report dates, counts, location, lease types and prices. We also won’t invade on what the lease is for, but rather what type it is. We are also focusing only on the city and part of San Diego rather than specific addresses. This way, we can see trends in different neighborhoods without invading on privacy. This data is public and provided by the city, so we are not exposing any data that isn’t already available.

[X] **C.5 Auditability**: Is the process of generating the analysis well documented and reproducible if we discover issues in the future?

- The process is well documented and reproducible since we’re using datasets collected by the San Diego County.


### D. Modeling

[X] **D.1 Proxy discrimination**: Have we ensured that the model does not rely on variables or proxies for variables that are unfairly discriminatory?

- Our pothole repair request data directly reflects our target prediction variable (frequency of pothole repair tickets). Reasonably, it may also be used as a proxy for actual pothole prevalence. The dataset includes data from the entirety of San Diego. Of course, factors such as unequal access to requests, repeat requests for the same potholes, and possible false reports are possible confounds for our model that should be addressed by acknowledgement and/or filtering our data. Our city property prices dataset allow us to examine the patterns of price fluctuation throughout the years. Again, this is a direct measure of our target variable (cost of property). It may be argued as a proxy for neighborhood wealth (e.g. the geographical clustering of more expensive properties vs less expensive properties) and be cross-examined with the geographical location of pothole request tickets. Importantly, the dataset includes the entirety of San Diego county and we do not intend to filter by area codes to avoid discriminatory patterns based on potential economic disparities. Our traffic volumes dataset is also a direct reflection of our target variable (traffic density). The dataset includes data from the entirety of San Diego county. 

[X] **D.2 Fairness across groups**: Have we tested model results for fairness with respect to different affected groups (e.g., tested for disparate error rates)?

- Considering that our datasets come from the same source and include data from areas across San Diego, we plan to minimize filtering based on geographical location. This is to avoid potentially discriminatory results that arise from selecting areas that are more or less wealthy. We should also plan to investigate potential disparities in data collection (e.g. the population’s access to report forms, data transparency, etc.) in order to consider how we should reasonably (re-)weigh the effects of our variables. 

[X] **D.3 Metric selection**: Have we considered the effects of optimizing for our defined metrics and considered additional metrics?

- We defined our metrics by choosing only relevant variables. We chose these by evaluating what factors our hypothesis focuses on and matching them to the columns of our dataset. The variables we chose such as location, lease type, price, date, and price all match our research. We want to evaluate how different parts of San Diego are affected and will match our 3 datasets by date to see if there’s correlations between pothole count, lease price, and traffic count. The lease type also let’s us know if the lease is for residential use. Researching different aspects such as traffic count vs. pothole count also let’s us not assume a conclusion and see if there’s other reasoning of pothole requests. 

[] **D.4 Explainability**: Can we explain in understandable terms a decision the model made in cases where a justification is needed?

- N/A

[X] **D.5 Communicate limitations**: Have we communicated the shortcomings, limitations, and biases of the model to relevant stakeholders in ways that can be generally understood?

- We’re specifically looking at city-owned properties because the potholes are on public property, meaning that the city is responsible for fixing them. We would also mention that any houses not owned by the city are not included in the data, mainly because it’s not publicly available, and to protect their personally identifiable information. The traffic patterns are also only taking into account the total number of traffic occurrences based on the location in relation to the houses. 

### E. Deployment

[X] **E.1 Monitoring and evaluation**: Do we have a clear plan to monitor the model and its impacts after it is deployed (e.g., performance monitoring, regular audit of sample predictions, human review of high-stakes decisions, reviewing downstream impacts of errors or low-confidence decisions, testing for concept drift)?

- In conjunction with other models or technologies that may measure actual pothole occurrence, we may be able to better ensure that our predictions are 1) accurate, 2) being enacted ethically/responsibly. In other words, if using our model is performing and enacted as intended, pothole occurrence may decrease or be more quickly resolved relative to current rates. If there are incongruencies in this expectation or 
if ethical disparities arise (e.g. lack of care of a particular region of San Diego), an alteration to our model may be required. 

[X] **E.2 Redress**: Have we discussed with our organization a plan for response if users are harmed by the results (e.g., how does the data science team evaluate these cases and update analysis and models to prevent future harm)?

- Because our hypothesis examines the relationship of pothole frequency, traffic volume, and city property costs in SD country. The analysis could reinforce existing inequalities by directing more attention and repair resources towards higher-property-value neighborhoods while undeserving lower-income areas. We would need to regularly evaluate outputs for geographic or socioeconomic bias. Compare predictions across neighborhoods to ensure lower-cost property are not systematically deprioritized. As well as establish feedback for residents, city officials and stakeholders can report concerns about unfair prioritization or inaccuracy in predictions. We would need to refrain and adjust the model periodically using up to date traffic, lease cost, and repair-request data to reduce bias and improve fairness and accuracy.

[X] **E.3 Roll back**: Is there a way to turn off or roll back the model in production if necessary?

- Yes there should be a plan to turn off or roll back model if it produces harmful, inaccurate, or biased results in production. Maintaining the ability to temporarily turn off the model by city planners or public infrastructure departments. Previous versions of models and datasets would be stored so we can roll back to earlier and more reliable version if bias is obvious. Wanna maintain accountability, transparency, and flexibility if there is unintended harm or inaccuracies.

[X] **E.4 Unintended use**: Have we taken steps to identify and prevent unintended uses and abuse of the model and do we have a plan to monitor these once the model is deployed?

- Our model intends to consider the entirety of San Diego county with the data that is available to us. We intend to avoid potentially discriminatory analysis and filtering of data, especially ones based on geographical area. Through writing, we also plan to acknowledge inequities in reporting access (via online forms, county offices, lack of education on reporting, etc.) as well as making a clear distinction between pothole repair requests and actual pothole prevalence. Our model primarily aims to provide predictive power over where potholes may occur more frequently. It does not directly address where repairs are actually being made or planned. Given an extended project, we could utilize technologies/programs that detect actual pothole prevalence + pothole repair and compare that with our model. Using this comparison, we may monitor if our model is subject to overreliance/overgeneralization leading to unequal care for parts of San Diego county (e.g. if repairs are only made in predicted “high-pothole request” areas while predicted “low-pothole request” areas never see repairs).

## Team Expectations

***Communication***:
- Form of communication: iMessage, FaceTime
- Expected response time: 24 hrs
- Meeting Frequency: Virtually; once a week


***Tone***:
- Casual, polite
- Compliment sandwich (example below)
- About opinions: “I” statements + further explanation on comment + possible alternatives/changes
- e.g. “I like how X turned out! However, I think we can improve on Y. Right now, it feels like (explanation)... Maybe we should try Z to improve this. I’m liking the direction so far though!”
- Opening the floor up to any unspoken ideas before moving from topic to topic


***Decision Making***:
- **Majority vote**; no one’s vote is weighted more or less than the next person
- If on a short time frame and waiting on a teammate to respond, majority vote for those who have voted.


***Task***:
- No group leader necessarily. Most capable/knowledgeable person about any certain task may take the lead if need be; for the most part, ***team-effort all the way***!
- Members may volunteer for tasks they want; members who are absent/have no preference will be handed with remaining unclaimed tasks.
- Depending on the task length/time commitment, we may rotate responsibilities to make obligations fair


***Struggling?***
- Check-Ins before assignment submission
- A struggling person can contact group via iMessage
- After struggling for an hour, the person should contact the group.
- The person who is knowledgeable about the issue should help first. Otherwise, the person who’s available should help first.
- Try to communicate any anticipated absences from team meetings **at least 2 hours** before scheduled time so accommodations can be arranged.

## Project Timeline Proposal

| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 4/28  |  7:30 PM | Look over COGS 108 Expectations Policies. Review Project proposal notebook and decide what sections to do independently | Determine best form of communication; Discuss and decide on final project topic; discuss hypothesis; begin background research |
| 5/5  |  2 PM |  Do background research on topic | Discuss ideal dataset(s) and ethics; draft project proposal |
| 5/12  | 2 PM  | Edit, finalize, and submit proposal; Search for datasets  | Discuss Wrangling and possible analytical approaches; Assign group members to lead each specific part   |
| 5/19  | 6 PM  | Import & Wrangle Data (Abby ; Nicole); EDA (Jeric) | Review/Edit wrangling/EDA; Discuss Analysis Plan   |
| 5/26  | 2 PM  | Finalize wrangling/EDA; Begin Analysis (Ynna; Nicole) | Discuss/edit Analysis; Complete project check-in |
| 6/2  | 12 PM  | Complete analysis; Draft results/conclusion/discussion (Abi)| Discuss/edit full project |
| 6/10  | Before 11:59 PM  | NA | Turn in Final Project & Group Project Surveys |